// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypvoijfxlfxiyoekxgzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwdm9pamZ4bGZ4aXlvZWt4Z3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyODkyMzIsImV4cCI6MjA2NTg2NTIzMn0.5ioNwuv2hyWXeIctDu0pljA8eBYf4eKpUwepu7SOSro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);